### PR TITLE
feat(cli): impl shell completion command (dev)

### PR DESCRIPTION
**Pull request by dan-da**
Addresses #158.

obsoletes #218.  (this PR applies to dev branch.  #218 applies to master)

Implements 'completion' command to output shell completions for bash, powershell, fish, zsh, etc, as supported by clap_complete crate.

Introduces a dependency on clap_complete and update clap dep to 4.0.18.

```
$ kindelia completion --help
Generate auto-completion for a shell

Usage: kindelia completion <SHELL>

Arguments:
  <SHELL>  The shell to generate completion for [possible values: bash, elvish, fish, powershell, zsh]

Options:
  -h, --help  Print help information
```

Example of usage in bash.

```
$ kindelia completion bash > /tmp/completions.bash

$ source /tmp/completions.bash 

$ kindelia <tab>
--api        --config     -h           init         publish      sign         util         
-c           deserialize  help         node         run-remote   test         -V           
completion   get          --help       post         serialize    unserialize  --version 

$ kindelia publish <tab>
-e         --encoded  <FILE>     -h         --help     
```

I kept this impl as simple as possible.  Future improvements could include:
* option to generate completions for all known shells and write each to a file.
* execute within build.rs to auto-generate completion files at compile time.

### CODE REVIEW

**Comment by dan-da** [comment]
I fixed a clippy error, squashed, and force-pushed.

**Comment by steinerkelvin** [comment]
Nice.

It's working with bash for me but not with zsh. I've got the following error:
```
kindelia-node on  shell_completion_dev [$!?] via 🦀 v1.65.0 
❯ kindelia completion zsh > kindelia_completion.zsh 

❯ source kindelia_completion.zsh
_arguments:comparguments:327: can only be called from completion function
```
Apparetly I need to write this file to some folder and set a env var.
Something like [this](https://github.com/zsh-users/zsh-completions#oh-my-zsh).

**Comment by steinerkelvin** [comment]
Nice.

It's working with bash for me but not with zsh. I've got the following error:
```
kindelia-node on  shell_completion_dev [$!?] via 🦀 v1.65.0 
❯ kindelia completion zsh > kindelia_completion.zsh 

❯ source kindelia_completion.zsh
_arguments:comparguments:327: can only be called from completion function
```
Apparetly I need to write this file to some folder and set a env var.
Something like [this](https://github.com/zsh-users/zsh-completions#oh-my-zsh).

**Comment by steinerkelvin** [comment]
Nice.

It's working with bash for me but not with zsh. I've got the following error:
```
kindelia-node on  shell_completion_dev [$!?] via 🦀 v1.65.0 
❯ kindelia completion zsh > kindelia_completion.zsh 

❯ source kindelia_completion.zsh
_arguments:comparguments:327: can only be called from completion function
```
Apparetly I need to write this file to some folder and set a env var. Something like [this](https://github.com/zsh-users/zsh-completions#oh-my-zsh).

**Comment by steinerkelvin** [comment]
Nice.

It's working with bash for me but not with zsh. I've got the following error:
```
kindelia-node on  shell_completion_dev [$!?] via 🦀 v1.65.0 
❯ kindelia completion zsh > kindelia_completion.zsh 

❯ source kindelia_completion.zsh
_arguments:comparguments:327: can only be called from completion function
```
Apparetly I need to write this file to some folder and set a env var. Something like [this](https://github.com/zsh-users/zsh-completions#oh-my-zsh).

**Comment by dan-da** [comment]
ok, yeah that seems a zsh specific thing.  installation/usage of the completions will of course vary by shell.

to be clear, I have only tested with bash locally.

that said, completions are generated by the `clap_complete` crate, so a) it should be fairly well tested and b) any 'doesn't work with shell X' issues should be reported there.

**Comment by dan-da** [comment]
I tried with zsh and got the same error.  I saw a couple bug reports about it. [1](https://github.com/clap-rs/clap/issues/3508) [2](https://github.com/volta-cli/volta/issues/496)

I was able to get it to work via:

```
$ kindelia completion zsh > /tmp/k.zsh
$ sudo mv /tmp/k.zsh /usr/share/zsh/vendor-completions/_kindelia
$ zsh
% kindelia completion <tab>
Completing shell -- The shell to generate completion for
bash        elvish      fish        powershell  zsh 
```

So that's something for an installer to be aware of.

**Comment by steinerkelvin** [comment]
I've done this on my config:

```sh
$ kindelia completion > ~/config/zsh-completions/_kindelia
```

```sh
.zshrc
------
dir="${HOME}/config/zsh-completions"
if [ -d "$dir" ]; then
    FPATH="$dir:${FPATH}"
fi
```

I'll document on README.

**Pull request merged**
