### PR TITLE
add `node clean blocks` command

### PR DESCRIPTION
**Pull request by racs4**
this command allows clear all, half, or a specific quantity of blocks from the file system

### CODE REVIEW

**Comment by steinerkelvin** [comment]
Why is this relevant?

**Comment by racs4** [comment]
It is just an utility command. It can be used if the user wants to save space or if some block got corrupted happens. Without this command, the user would have to delete all folder or find the last blocks and delete them manually (it can be hard if there are many blocks and you don't know the exact last height).

**Comment by steinerkelvin** [comment]
Can you add the command examples to the top comment on `cli.rs` ?

**Comment by racs4** [comment]
> Can you add the command examples to the top comment on `cli.rs` ?

Done in 2ae3375

**Pull request merged**
